name: Run Fooocus on CPU

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fooocus-job:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Use the required Python version

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt in your repo

    # Step 4: Run Fooocus script (replace with your entry script)
    - name: Run Fooocus Image Generation
      run: |
        python main.py  # Replace with the entry point script for Fooocus

    # Step 5: (Optional) Upload generated images as artifacts
    - name: Upload generated images
      uses: actions/upload-artifact@v2
      with:
        name: generated-images
        path: output_images/  # Replace with the correct directory
